# Generated by Django 2.1.2 on 2018-10-18 06:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.EmailField(max_length=40)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('addr', models.TextField()),
            ],
        ),
    ]
