# Generated by Django 2.1.2 on 2018-10-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.BooleanField(choices=[('M', 'Male'), ('F', 'Female')], default=True),
        ),
    ]
