# Generated by Django 2.1.2 on 2018-10-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20181018_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.BooleanField(choices=[('true', 'Male'), ('false', 'Female')], default=True),
        ),
    ]
