# Generated by Django 2.1.2 on 2018-10-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20181018_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.BooleanField(choices=[('True', 'Male'), ('False', 'Female')], max_length=1, verbose_name='Gender'),
        ),
    ]
