# Generated by Django 2.1.2 on 2018-10-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20181018_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[(True, 'Male'), (False, 'Female')], max_length=1, verbose_name='Gender'),
        ),
    ]
