# Generated by Django 2.1.2 on 2018-10-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_auto_20181018_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')]),
        ),
    ]
