# Generated by Django 2.1.2 on 2018-10-24 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_remove_member_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
