# Generated by Django 2.1.2 on 2018-10-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_member_bgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
