# Generated by Django 2.1.2 on 2018-10-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_auto_20181024_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='email',
            new_name='email_address',
        ),
    ]
