# Generated by Django 2.1.2 on 2018-10-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_auto_20181024_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email_address',
            field=models.EmailField(help_text='Enter Email.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(help_text='Enter Name.', max_length=40),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True),
        ),
    ]
